name: pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - tqdm
  - pyyaml
  - pytorch
  - torchvision
  - datasets
  - tokenizers